apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding
roleRef:
  name: nginx-role
  kind: Role
subjects:
- kind: ServiceAccount
  name: nginx
  namespace: nginx-namespace
