apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route
  labels:
    app: nginx-deployment
    environment: dev
spec:
  host: nginx-route-webapp.local
  to:
    kind: Service
    name: nginx-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
route
