apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: webapp
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: nginx
    tier: frontend
  type: NodePort
